name: Bump version

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  bump-version:
    name: Bump app version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commit type
        run: |
          echo COMMIT_TYPE=$(echo ${{ github.event.head_commit.message }} \
          | grep -o '\(feat\|chore\|fix\)\(!\?\)\:' \
          | grep -o '\(feat\|chore\|fix\)\(!\?\)') >> $GITHUB_ENV

      - name: Is major bump
        if: 'contains(fromJson(''["feat!", "chore!", "fix!"]''), ${{ env.COMMIT_TYPE }})'
        run: echo "${{ env.COMMIT_TYPE}} Is major bump"

      - name: Is minor bump
        if: "${{ env.COMMIT_TYPE }} == 'feat'"
        run: echo "${{ env.COMMIT_TYPE }} Is minor bump"

      - name: Is patch bump
        if: 'contains(fromJson(''["chore", "fix"]''), ${{ env.COMMIT_TYPE }})'
        run: echo "${{ env.COMMIT_TYPE }}Is patch bump"
