name: Bump version

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  bump-version:
    name: Bump app version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commit type
        run: |
          echo COMMIT_TYPE=$(echo ${{ github.event.head_commit.message }} \
          | grep -o '\(feat\|chore\|fix\)\(!\?\)\:' \
          | grep -o '\(feat\|chore\|fix\)\(!\?\)') >> $GITHUB_ENV

      - name: Check bump type
        run: |
          if [ ("feat!" "chore!" "fix!")[@] =~ ${{ env.COMMIT_TYPE }} ]; then \
            echo "Is major bump"
          elif [ ("chore" "fix")[@] =~ ${{ env.COMMIT_TYPE }} ]; then \
            echo "Is patch bump"
          elif [ ${{ env.COMMIT_TYPE }} == "feat" ]; then \
            echo "Is minor bump"
          fi
