name: Bump version

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  bump-version:
    name: Bump app version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commit type
        run: |
          echo COMMIT_TYPE=$(echo ${{ github.event.head_commit.message }} \
          | grep -o '\(feat\|chore\|fix\)\(!\?\)\:' \
          | grep -o '\(feat\|chore\|fix\)\(!\?\)') >> $GITHUB_ENV

      - name: Is major bump
        if: ${{ contains(fromJSON('["feat!", "chore!", "fix!"]'), env.COMMIT_TYPE ) }}
        run: |
          echo BUMP_TYPE=major >> $GITHUB_ENV

      - name: Is minor bump
        if: ${{ env.COMMIT_TYPE == 'feat' }}
        run: |
          echo BUMP_TYPE=minor >> $GITHUB_ENV

      - name: Is patch bump
        if: ${{ contains(fromJSON('["chore", "fix"]'), env.COMMIT_TYPE ) }}
        run: |
          echo BUMP_TYPE=patch >> $GITHUB_ENV

      - name: Bump is not detected
        if: ${{ env.BUMP_TYPE == '' }}
        run: |
          echo "There was no bump detected :-("
          exit 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Bump version
        run: |
          npm version --commit-hooks false --git-tag-version false ${{ env.BUMP_TYPE }}

      - name: Get new version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create a new branch
        env:
          BRANCH_NAME: v${{ steps.package-version.outputs.current-version }}
        run: |
          date > generated.txt
          git checkout -b $BRANCH_NAME
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Bump app to version ${{ steps.package-version.outputs.current-version }}"
          git push origin $BRANCH_NAME

      - name: create pull request
        env:
          BRANCH_NAME: v${{ steps.package-version.outputs.current-version }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh pr create -B main -H $BRANCH_NAME --title $BRANCH_NAME --body 'Created by Github action'